projects:
  boilerplate:
    schemaPath: amplify/backend/api/boilerplate/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: graphql
        region: us-east-1
        apiId: null
        maxDepth: 2
